version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: READER_DB
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: user
      MYSQL_PASSWORD: 123


  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin:latest
    # Connect to "my-network" network, as defined below

    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "80:8080"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
    # Wait for "mysql" container to start first
    depends_on:
      - mysql



  mysql2:
    image: mysql:8.0
    ports:
      - "6446:6446"
    environment:
      MYSQL_DATABASE: WRITER_DB
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: user
      MYSQL_PASSWORD: 123


  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php","/var/www/laravel/artisan"]


  node:
    build:
      context: dockerfiles
      dockerfile: node.Dockerfile
    volumes:
      - ./src:/var/www/laravel



