version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  mysql:
    image: mysql:8.0
    container_name: db-master
    volumes:
      - ./env/master.cnf:/etc/my.cnf.d/repl.cnf
      - ./env/master.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: "123"

  mysqlread:
    image: mysql:8.0
    container_name: db-slave1
    volumes:
      - ./env/slave1.cnf:/etc/my.cnf.d/repl.cnf
      - ./env/slave.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php","/var/www/laravel/artisan"]


  node:
    build:
      context: dockerfiles
      dockerfile: node.Dockerfile
    volumes:
      - ./src:/var/www/laravel



